# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, ... }:

{
  fileSystems."/persist" =
    {
      device = "/dev/disk/by-label/amayadori_persist";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "defaults" "subvol=@persist" "ssd" "nodiscard" "rw" "noatime" "compress=zstd" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-partuuid/bad2f515-3b28-4b52-aa46-959b6406e0ef";
      fsType = "vfat";
    };
  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "defaults" "size=2G" "mode=755" ];
    neededForBoot = true;
  };

  swapDevices = lib.mkForce [
    {
      device = "/dev/disk/by-partlabel/_swap";
    }
  ];
}