logo = Image("hack_small.png");

sprite = Sprite(logo);

screen_width = Window.GetWidth();
screen_height = Window.GetHeight();

sprite.SetX((screen_width - logo.GetWidth()) / 2);
sprite.SetY((screen_height - logo.GetHeight()) / 2);

opacity = 0;
direction = 1;

fun refresh() {

    opacity += direction * 0.02;

    if (opacity >= 1) {
        direction = -1;
    }

    if (opacity <= 0.3) {
        direction = 1;
    }

    sprite.SetOpacity(opacity);
}

Plymouth.SetRefreshFunction(refresh);